services:
  - type: web
    name: tech-elevate-backend
    env: python
    region: oregon
    plan: free
    buildCommand: pip install -r backend/requirements.txt
    startCommand: python backend/app.py
    autoDeploy: true
    repo: https://github.com/vedikalohiya/TechElevate
    branch: main

  - type: static
    name: tech-elevate-frontend
    env: static
    region: oregon
    plan: free
    buildCommand: ''
    publishPath: frontend
    repo: https://github.com/vedikalohiya/TechElevate
    branch: main
